# Generated by Django 3.1.1 on 2021-01-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_images_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='url',
            field=models.URLField(default='http://www.google.com'),
        ),
    ]
